
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sahilya
 */
public class Faculty extends javax.swing.JFrame {

    /**
     * Creates new form Faculty
     */
    public Faculty() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subject_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fac_nme = new javax.swing.JTextField();
        daa = new javax.swing.JRadioButton();
        os = new javax.swing.JRadioButton();
        se = new javax.swing.JRadioButton();
        toc = new javax.swing.JRadioButton();
        lab_daa = new javax.swing.JRadioButton();
        lab_os = new javax.swing.JRadioButton();
        pij = new javax.swing.JRadioButton();
        osst = new javax.swing.JRadioButton();
        co = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        usernme = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tot_lec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lec_attend = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        percent = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 16)); // NOI18N
        jLabel1.setText("FACULTY INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FACULTY NAME");

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COURSE NAME");

        fac_nme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        daa.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(daa);
        daa.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        daa.setForeground(new java.awt.Color(255, 255, 255));
        daa.setText("DAA");
        daa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daaActionPerformed(evt);
            }
        });

        os.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(os);
        os.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        os.setForeground(new java.awt.Color(255, 255, 255));
        os.setText("OS");
        os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osActionPerformed(evt);
            }
        });

        se.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(se);
        se.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        se.setForeground(new java.awt.Color(255, 255, 255));
        se.setText("SE");
        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });

        toc.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(toc);
        toc.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        toc.setForeground(new java.awt.Color(255, 255, 255));
        toc.setText("TOC");
        toc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tocActionPerformed(evt);
            }
        });

        lab_daa.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(lab_daa);
        lab_daa.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        lab_daa.setForeground(new java.awt.Color(255, 255, 255));
        lab_daa.setText("LAB DAA");
        lab_daa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_daaActionPerformed(evt);
            }
        });

        lab_os.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(lab_os);
        lab_os.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        lab_os.setForeground(new java.awt.Color(255, 255, 255));
        lab_os.setText("LAB OS");
        lab_os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_osActionPerformed(evt);
            }
        });

        pij.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(pij);
        pij.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        pij.setForeground(new java.awt.Color(255, 255, 255));
        pij.setText("LAB PiJ");
        pij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pijActionPerformed(evt);
            }
        });

        osst.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(osst);
        osst.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        osst.setForeground(new java.awt.Color(255, 255, 255));
        osst.setText("LAB OSST");
        osst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osstActionPerformed(evt);
            }
        });

        co.setBackground(new java.awt.Color(44, 62, 80));
        Subject_group.add(co);
        co.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        co.setForeground(new java.awt.Color(255, 255, 255));
        co.setText("CO");
        co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(fac_nme, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(daa)
                        .addGap(18, 18, 18)
                        .addComponent(co)
                        .addGap(18, 18, 18)
                        .addComponent(os)
                        .addGap(18, 18, 18)
                        .addComponent(se)
                        .addGap(18, 18, 18)
                        .addComponent(toc)
                        .addGap(18, 18, 18)
                        .addComponent(lab_daa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_os)
                        .addGap(4, 4, 4)
                        .addComponent(pij)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(osst)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fac_nme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(daa)
                    .addComponent(os)
                    .addComponent(se)
                    .addComponent(toc)
                    .addComponent(lab_daa)
                    .addComponent(lab_os)
                    .addComponent(pij)
                    .addComponent(osst)
                    .addComponent(co))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 16)); // NOI18N
        jLabel2.setText("UPDATE ATTENDANCE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STUDENT USERNAME");

        usernme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usernme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernmeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL LECTURES");

        tot_lec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LECTURES ATTENDED");

        lec_attend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PERCENTAGE");

        percent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        UpdateButton.setBackground(new java.awt.Color(44, 62, 80));
        UpdateButton.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernme, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(lec_attend))
                        .addGap(141, 141, 141)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(UpdateButton)))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tot_lec, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(percent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tot_lec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lec_attend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(UpdateButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernmeActionPerformed

    private void tocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tocActionPerformed
        // TODO add your handling code here:
        subject = "TOC";
    }//GEN-LAST:event_tocActionPerformed

    private void osstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osstActionPerformed
        // TODO add your handling code here:
        subject = "OSST";
    }//GEN-LAST:event_osstActionPerformed

    private void daaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daaActionPerformed
        // TODO add your handling code here:
        subject = "DAA";
    }//GEN-LAST:event_daaActionPerformed

    private void coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coActionPerformed
        // TODO add your handling code here:
        subject = "CO";
    }//GEN-LAST:event_coActionPerformed

    private void osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osActionPerformed
        // TODO add your handling code here:
        subject = "OS";
    }//GEN-LAST:event_osActionPerformed

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        // TODO add your handling code here:
        subject = "SE";
    }//GEN-LAST:event_seActionPerformed

    private void lab_daaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_daaActionPerformed
        // TODO add your handling code here:
        subject = "LAB-DAA";
    }//GEN-LAST:event_lab_daaActionPerformed

    private void lab_osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_osActionPerformed
        // TODO add your handling code here:
        
        subject = "LAB-OS";
    }//GEN-LAST:event_lab_osActionPerformed

    private void pijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pijActionPerformed
        // TODO add your handling code here:
        subject = "LAB-PiJ";
    }//GEN-LAST:event_pijActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
           String fac_name    = fac_nme.getText();
       // String subject    = jTextFieldlname.getText();
        String username = usernme.getText();
      
        String total_lec = tot_lec.getText().toString();
        double final_total_lec = Double.parseDouble(total_lec);
        
        String attended_lec   = lec_attend.getText().toString();
        double final_attended_lec = Double.parseDouble(attended_lec);
        System.out.println(final_attended_lec);
      //  String percentage     = percent.getText();
        double percentage = Math.round((final_attended_lec/final_total_lec) * (100));
        
        String str = String.valueOf(percentage);
        
        System.out.println(str);
        percent.setText(str);
         try{
            
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver connected....");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/faculty","user","12345678");
            PreparedStatement ps =con.prepareStatement("insert into attendance values(?,?,?,?,?,?)");
            ps.setString(1, fac_name);
            ps.setString(2, subject );
            ps.setString(3, username);
            ps.setString(4, total_lec);
            ps.setString(5, attended_lec);
            ps.setDouble(6, percentage);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Attendance Updated Succesfully.");
            
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Subject_group;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JRadioButton co;
    private javax.swing.JRadioButton daa;
    private javax.swing.JTextField fac_nme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton lab_daa;
    private javax.swing.JRadioButton lab_os;
    private javax.swing.JTextField lec_attend;
    private javax.swing.JRadioButton os;
    private javax.swing.JRadioButton osst;
    private javax.swing.JTextField percent;
    private javax.swing.JRadioButton pij;
    private javax.swing.JRadioButton se;
    private javax.swing.JRadioButton toc;
    private javax.swing.JTextField tot_lec;
    private javax.swing.JTextField usernme;
    // End of variables declaration//GEN-END:variables
    private String subject;

}
